### ISSUE TITLE
Increase flexibility for parameter experiments

### ISSUE THREAD

**Issue by nilsnevertree** [nilsnevertree/kalman-reconstruction-partially-observed-systems#76]
It would be helpful to increase flexibility of parameter experiments.
Up to now, only this is possible:
````yaml
# ...
    modified_arguments : ["arg1", "arg2"]
    factors :  [0.5, 1, 2]
# ...
````
But it would be handy to additionally be able to set other parameters.
````yaml
    # step 2
    modified_arguments : ["arg1", "arg2"]
    factors :  [0.5, 1, 2]
    # step 3
    # The values in default settings and given by the modified arguments (step 2) will be OVERRIDDEN by the lists provided in this dictionary.
    modified_settings : {
        arg3 : ["bla", "bli", "blub", ],
        arg2 : [-1, 3, 9, ],
    }
````
